# Generated by Django 3.2.7 on 2023-07-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Contact',
        ),
    ]
